name: glassify
description: >
  A lightweight Flutter package for building customizable glassmorphism effects with blur, 
  translucency, and theme-aware styling. 


version: 0.0.6
homepage: https://github.com/Alto-b/packages
repository: https://github.com/Alto-b/Flutter-Packages/tree/main/glassify
issue_tracker: https://github.com/Alto-b/packages/issues
documentation: https://github.com/Alto-b/packages/tree/main/glassify#readme
license: MIT

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
